### PR TITLE
Lr missionstatement

### PR DESCRIPTION
**Pull request by rousell**
Testing
- Go to the employees page from index via link
- Make sure the page looks like the mockup!
- Use the link to go back to the index (all dinos) page

Note: we didn't add the nav bar since that's on a different ticket

### CODE REVIEW

**Comment by zoeames** [comment]
@rousell can you put employees.html into an html directory?

**Comment by rousell** [comment]
Okay! Added the html directory

**Comment by morecallan** [comment]
👍

**Comment by zoeames** [comment]
👍

**Pull request merged**
